import localFont from "next/font/local";
import "./globals.css";
import Navigation from "@/components/Navigation";
import { FirebaseProvider } from "@/context/FirebaseContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://www.google.com/recaptcha/enterprise.js?render=6Ldfq1oqAAAAAF0Oz5jnXZqsXzXbv6HOHT9xRXu5"></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <Navigation />
        <FirebaseProvider>{children}</FirebaseProvider>
      </body>
    </html>
  );
}
